# 服务器端口号
server:
  port: 8081
  servlet:
    context-path: /alipayDemo
# 项目系统参数配置
spring:
  application:
    name: springboot_alipay_demo
  # json字符串中时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 前端渲染模板
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

alipay:
  config:
    appId: 9021000122695159
    privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCrvPw1p2iWJbvjhzFG0SN+g/3pPo/oPIyfrvrbLa4L5yJQ3u7C52osGKBdGjJktgd41CXB0jekuV3cRNBJCKo1Bqi1naPE0mxHn5eqpzmJJOIPU3adnQkrCHSTsOJ+hOCIEn9yQiP9hP/URXdzxK0EcTeWcUCLCtXST1j8vM8cWlI13CSw8U8jDnHZaOrbx8R/oM/2TZMiR4JmTUlINc+VyRIW4msxmsvofrLjNYz9TVVqrGXe8n5oin3UmQZ+Bnx85+1RSAY7IXaxhmi59fW+mRz4VxBdlAfanpp1m4Mmwtaqfy/HSwJQ57CfyyDZYVskPAMp4Bq8hN6i9fhAxT/FAgMBAAECggEBAIYpx2Yq+DuEEvo23ToTnAT0HGIgq8+jrb/5tKORVgyabmZ7Ik9E9d6pBm51TrT6t2+fXDfEgA/BeB/h6k2D5WQzZY0sL4pNUKXLeXKp3PrUw31xmJKc4VKq8leGsgpgx//FY6bhILinNCyicCUSmo+D2wc+RkvZFR2NO1mGLs5YQVeLOpCOOkNBm5MWPCe2dQQfbHyWgEHoSA3BrgUHVbHyYL8N5i4bn8JOz2bQdFV42f57TC/WL0Mkre3zxM+zjZZCh4TMXKU7wrdwcy2vRIqh5qoCcSNUca3EUUXNfOZ1NHpEndtWTsv7GCUTe4hNs1awAaITeV/8VpZ8Z6xooYECgYEA2ZgxUpcmQECo+3mOBK+0qb1XTeCMvhbu5St/WMWgTf/Rn/hFN6kRpqIWMP4/HtLUTOUPKCOFc3GzIuBV9KxasUFQE9wLTAq2HNsxA8CGDyD6v6+F23aFCv+XMYoy6vLLZfPTFqPTPZ+USX0zSHdFboGMDH/yfcKlMRFu+gZkWhECgYEAygzRmgeWqXkVNxGIcI7OMC1HdHwAlyjssz2JMBvpyS6kZil2FWbyBTbQlTod3bsK4bQo2m69uHHBnnvPDR8aLocQxnh3ytoQXhyFPkMeJYI3H7ZlXeAUkqkOmE0CMnB1Wbw8rFgy9wh/7xl+oZeYUi1yMIQAS/ITKsoLaE7gtnUCgYEA01pB5lAMhnKH8KPUL3cfi5Pu/iTzcBxEdXL3ohlrqPen/LMhQHxHOczMs0/xrZXpQrtnKny+PjEdZ+3xb9QNz4h6KKAelQD+fS7nABb74CwPgysRYOdROSqkCCmNZarpqCDaU25TW9LqLSugKW44karhhq6ssjzjSbL+UXrt9JECgYAHLV1ks1BOxNZUFnNaTDhWzcT0BlOfCv0dgNoWs2cill2Qo3hmWjnOpZvTMTVOYw6H5fZti/GBU8kk8BDyzmAHtxSJeE4JDqX2Md0p0QiJHI8IuVnwc71HWGoETvf9ArGodl9RX/CvhcXFoIo3A0ON579eqdG44Oh9ZJ/zHJou4QKBgQCU29k+Z9sUNiqkZA0EqUof39FGE61U2GiODy3df+x3cXTLErligDIhorJBjEESG0vgfk2vbBr1OHsj25Oz/zOuOwS+U1zn2t+wZWufCMjCj4dWO6pBT4KD/U6X3pNGbCsol3e+/gIp0JMhLyBDk5CwOkEKxlJkOzdk6gxW9F22Cw==
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl86MVgtrrJxf65VH08Nj5cPEkOJUNFPn84qthUw9E7VkX7hzAdfDk/LwfzZ6JFhS5lsRVHg7rL8LF+/7Fd0DKaM6qHvIN7QB+gEO2cUxh9XAPjid+MXVqRTPjGHM7aa8LXx3vtfTleWa941oPlq2vV/BJZ7JL1n+nyoBqAmp2zQeDq4WbGIBc61eTDCcxVUgGz39ZqhR/3IdLmPm/bJOFnuSzeyOcbHYsjVmJMkXyA1E3Dd/IA3Acgh8JP2k7nnkVG+km8jfMAy0MaDwTncYSJCVDX8cZ4+LmV4KrFwcB9vau+DZioj/BvqnYTmDtKC2GBrqW3M5CMYu/1p3keiKwQIDAQAB
    notifyUrl: http://localhost:8081/alipay/success
    returnUrl: http://localhost:8081/alipay/success
    signType: RSA2
    charset: UTF8
    gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do