server:
  port: 9090

wx:
  pay:
    appId: 123 #微信公众号或者小程序等的appid
    mchId: 123 #微信支付商户号
    mchKey: 123 #微信支付商户密钥
    subAppId: 123 #服务商模式下的子商户公众账号ID
    subMchId: 123 #服务商模式下的子商户号
    keyPath: classpath*:/*.p12 # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）